# Generated by Django 3.2.4 on 2021-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('whatsapp', models.BooleanField(default=False)),
                ('viber', models.BooleanField(default=False)),
                ('telegram', models.BooleanField(default=False)),
            ],
        ),
    ]
